version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 200
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
