---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Generic EC2"
Parameters:
  VPCID:
    Description: "VPC from Generic VPC Stack"
    Type: String

  PublicSubnet1:
    Description: "Subnet From Generic VPC Stack"
    Type: String

  PublicSubnet2:
    Description: "Subnet From Generic VPC Stack"
    Type: String

  SecurityGroup:
    Description: "SecurityGroup From Generic VPC Stack"
    Type: String

Mappings:
  Name:
    Instance:
      "Instance": "webserver-1"

Resources:
  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
      - !Ref EC2InstanceIAMRole
  EC2InstanceIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy'
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref EC2InstanceProfile
      InstanceType: t2.micro
      ImageId: "ami-0947d2ba12ee1ff75"
      KeyName: "eskool-infra-key"
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref PublicSubnet1 
      Monitoring: true
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeSize: 10
          VolumeType: gp2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          amazon-linux-extras enable nginx1
          yum install nginx -y
          yum update -y && yum install -y ruby wget && wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install && chmod +x ./install && ./install auto && service codedeploy-agent start
          /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource EC2Instance
      Tags:
      - Key: "Name"
        Value: !FindInMap [Name, Instance, Instance]
      - Key: DeploymentGroup
        Value: !Ref AWS::StackName
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M

Outputs:
  EC2Instance1InstanceID:
    Description: The Instance ID
    Value: !Ref EC2Instance
  EC2Instance1PublicIp:
    Description: The Instance Public IP
    Value: !GetAtt EC2Instance.PublicIp
