--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      vars: 
        empty_dirs: 
          - /tmp/test2
          - /tmp/test3
    - 
      debug: "msg=\"{{ lookup('env','BUILD_TAG') }}\""
      name: "Display the config"
    - 
      name: "cache clear"
      shell: "rm -rf /tmp/test/*"
    - 
      file: "state=absent path={{ item }}"
      with_items: empty_dirs
    - 
      file: "state=directory path={{ item }}"
      with_items: empty_dirs
