---
- hosts: all
  become: yes
  tasks:
    - name: Display the config
      debug: msg="{{ lookup('env','BUILD_TAG') }}"
    - name: cache clear
      shell: "rm -rf /tmp/test/*"
    - find: path=/tmp/test2 file_type=file
      register: files
    - find: path=/tmp/test2 file_type=directory
      register: directories
    - file: state=absent path={{ item.path }}
      with_items: 
        - "{{ files }}"
        - "{{ directories }}

