---
- hosts: all
  become: yes
  tasks:
    - name: Display the config
      debug: msg="{{ lookup('env','BUILD_TAG') }}"
    - name: cache clear
      shell: "rm -rf /tmp/test/*"
    - name: remove web dir contents
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/tmp/test2/*"
        - "/tmp/test3/*"
