---
- hosts: all
  become: yes
  tasks:
    - name: Display the config
      debug: msg="{{ lookup('env','BUILD_TAG') }}"
    - name: cache clear
      shell: "rm -rf /tmp/test2/*"
      args:
        warn: false